project_id = "slqtoxxvmazrjshekspn"

[functions.drug-interactions]
verify_jwt = true

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.create-video-room]
verify_jwt = true

[functions.send-prescription]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.public-prescription]
verify_jwt = false

[functions.ai-anomaly-rx]
verify_jwt = true

[functions.ai-outbreak-detect]
verify_jwt = true

[functions.ai-credit-risk]
verify_jwt = true

[functions.ai-reorder-forecast]
verify_jwt = true