apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: careconnect-web
  namespace: careconnect
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - careconnect.health
        - www.careconnect.health
      secretName: careconnect-tls
  rules:
    - host: careconnect.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: careconnect-web
                port:
                  number: 80
    - host: www.careconnect.health
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: careconnect-web
                port:
                  number: 80