/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ConsultIdRouteImport } from './routes/consult.$id'
import { Route as RxTokenRouteImport } from './routes/rx.$token'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'

const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const PosRoute = PosRouteImport.update({ id: '/pos', path: '/pos', getParentRoute: () => rootRouteImport } as any)
const PatientsRoute = PatientsRouteImport.update({ id: '/patients', path: '/patients', getParentRoute: () => rootRouteImport } as any)
const InventoryRoute = InventoryRouteImport.update({ id: '/inventory', path: '/inventory', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const ClaimsRoute = ClaimsRouteImport.update({ id: '/claims', path: '/claims', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AppointmentsRoute = AppointmentsRouteImport.update({ id: '/appointments', path: '/appointments', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const PatientsIdRoute = PatientsIdRouteImport.update({ id: '/$id', path: '/$id', getParentRoute: () => PatientsRoute } as any)
const ConsultIdRoute = ConsultIdRouteImport.update({ id: '/consult/$id', path: '/consult/$id', getParentRoute: () => rootRouteImport } as any)
const RxTokenRoute = RxTokenRouteImport.update({ id: '/rx/$token', path: '/rx/$token', getParentRoute: () => rootRouteImport } as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({ id: '/auth/phone', path: '/auth/phone', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/claims': typeof ClaimsRoute
  '/consult/$id': typeof ConsultIdRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/patients': typeof PatientsRouteWithChildren
  '/patients/$id': typeof PatientsIdRoute
  '/pos': typeof PosRoute
  '/rx/$token': typeof RxTokenRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/claims': typeof ClaimsRoute
  '/consult/$id': typeof ConsultIdRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/patients': typeof PatientsRouteWithChildren
  '/patients/$id': typeof PatientsIdRoute
  '/pos': typeof PosRoute
  '/rx/$token': typeof RxTokenRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/appointments' | '/auth' | '/auth/phone' | '/claims' | '/consult/$id' | '/dashboard' | '/inventory' | '/patients' | '/patients/$id' | '/pos' | '/rx/$token' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/appointments' | '/auth' | '/auth/phone' | '/claims' | '/consult/$id' | '/dashboard' | '/inventory' | '/patients' | '/patients/$id' | '/pos' | '/rx/$token' | '/settings'
  id: '__root__' | '/' | '/admin' | '/appointments' | '/auth' | '/auth/phone' | '/claims' | '/consult/$id' | '/dashboard' | '/inventory' | '/patients' | '/patients/$id' | '/pos' | '/rx/$token' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  ClaimsRoute: typeof ClaimsRoute
  ConsultIdRoute: typeof ConsultIdRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PosRoute: typeof PosRoute
  RxTokenRoute: typeof RxTokenRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/pos': { id: '/pos'; path: '/pos'; fullPath: '/pos'; preLoaderRoute: typeof PosRouteImport; parentRoute: typeof rootRouteImport }
    '/patients': { id: '/patients'; path: '/patients'; fullPath: '/patients'; preLoaderRoute: typeof PatientsRouteImport; parentRoute: typeof rootRouteImport }
    '/inventory': { id: '/inventory'; path: '/inventory'; fullPath: '/inventory'; preLoaderRoute: typeof InventoryRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/claims': { id: '/claims'; path: '/claims'; fullPath: '/claims'; preLoaderRoute: typeof ClaimsRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/appointments': { id: '/appointments'; path: '/appointments'; fullPath: '/appointments'; preLoaderRoute: typeof AppointmentsRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/patients/$id': { id: '/patients/$id'; path: '/$id'; fullPath: '/patients/$id'; preLoaderRoute: typeof PatientsIdRouteImport; parentRoute: typeof PatientsRoute }
    '/consult/$id': { id: '/consult/$id'; path: '/consult/$id'; fullPath: '/consult/$id'; preLoaderRoute: typeof ConsultIdRouteImport; parentRoute: typeof rootRouteImport }
    '/rx/$token': { id: '/rx/$token'; path: '/rx/$token'; fullPath: '/rx/$token'; preLoaderRoute: typeof RxTokenRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/phone': { id: '/auth/phone'; path: '/auth/phone'; fullPath: '/auth/phone'; preLoaderRoute: typeof AuthPhoneRouteImport; parentRoute: typeof rootRouteImport }
  }
}

interface PatientsRouteChildren { PatientsIdRoute: typeof PatientsIdRoute }
const PatientsRouteChildren: PatientsRouteChildren = { PatientsIdRoute: PatientsIdRoute }
const PatientsRouteWithChildren = PatientsRoute._addFileChildren(PatientsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AdminRoute, AppointmentsRoute, AuthRoute, AuthPhoneRoute, ClaimsRoute, ConsultIdRoute,
  DashboardRoute, InventoryRoute, PatientsRoute: PatientsRouteWithChildren, PosRoute, RxTokenRoute, SettingsRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>> }
}
